gp-seattle/rms-app

- CODEOWNERS
- To enforce that a code approval from either Daniel, James or Jeremy is needed for code to be pushed to master.
> RMS-5: Add CODEOWNERS file

- .gitignore
- amplify/backend/tsconfig.json
- package-lock.json
- package.json
- Created new tsconfig.json in amplify backend directory
- Backend stuff needs different tsc logic
> RMS-7: Configure Backend Typescript Config

- tsconfig.json
Improves frontend compile speed by a lot.
> RMS-8: Exclude amplify for frontend tsc

- .github/workflows/amplify.yml
- Needs to be initialized before push.
- Also changed name to CD, since that is more accurate.
> RMS-10: Amplify Init before Push

- .github/workflows/amplify-cd.yml
- Syntax is wrong
- Actually tested in Github UI, to make sure that it works.
> RMS-31: Fix AmplifyCD Github Action script

- .github/workflows/amplify-cd.yml
- .github/workflows/backend-pr-tests.yml
- metro.config.js
- Fix Github Action path syntax
- Fix Expo capability with Amplify
> RMS-36: Misc Bug Fix

- .github/workflows/backend-ci.yml
- .gitignore
- amplify/backend/resources/scripts/run-tests.sh
- package.json
- Modify Backend CI GitHub script
- Changes how the Jest Coverage Report gets outputed for it.
> GH-22: Add Jest Coverage Report to PRs

- .github/workflows/backend-ci.yml
- amplify/backend/ts-code/__dev__/db/LocalDBClient.ts
- amplify/backend/ts-code/__tests__/api/UpdateTags.test.ts
- amplify/backend/ts-code/src/api/GetItem.ts
> GH-24: Remove Unused Imports

- backend-build.js
> GH-43: Fix SMS Router Build

- amplify/backend/function/BorrowItem/BorrowItem-cloudformation-template.json
> GH-65: Borrow Item bug

- .github/workflows/amplify-cd.yml
Need to pass in Google Credentials.
resolves #90
> GH-90: Fix Amplify CD Scripts for Auth

- amplify/backend/storage/items/items-cloudformation-template.json
- amplify/backend/storage/items/parameters.json
> GH-100: Fix Item DDB Table

- App.js
- package-lock.json
- package.json
ran `npm install react-native-paper`  and tested that it shows up on my phone. Should be good to go.
> GH-133: install react-native-paper to npm

- frontend/App.js
- frontend/components/CounterExample/index.js
- frontend/store/sliceManager.js
- frontend/store/slices/counterSlice.js
- frontend/store/store.js
- package-lock.json
- package.json
Fixes #107 
(This is Gavin btw. Navig is an anagram of Gavin actually, just so that it's easier to remember.)
So, for the Redux setup, I created two main files: sliceManager.js and store.js. The other files are mainly as an example, so you can just ask me to remove them once you have seen how it works if you want. 
The sliceManager is built to be a basic layer on top of Redux/Redux Toolkit, which removes the jargon and generally makes the whole thing easier to work with. It provides a function to convert a "layout" function (which is super easy to make) into a Redux Toolkit slice, which is just a part of the overall state. It also gives two React hooks to access the slice: one to call the functions defined in the slice, and another to monitor changes to a particular value in the state. …
> GH-107/NavigSB - Redux Management System

- amplify/backend/ts-code/src/db/ItemTable.ts
> GH-131: Fix ItemTable key

- .github/workflows/amplify-cd.yml
- amplify/backend/storage/items/items-cloudformation-template.json
- amplify/backend/storage/items/parameters.json
> GH-133: Update key for items table

- amplify/backend/api/rms/schema.graphql
- amplify/backend/resources/seeds/one-name-borrowed.json
- amplify/backend/resources/seeds/one-name-returned.json
- amplify/backend/resources/seeds/two-names-one-batch-borrowed.json
- amplify/backend/resources/seeds/two-names-one-batch-partially-borrowed.json
- amplify/backend/resources/seeds/two-names-one-batch-returned.json
- amplify/backend/ts-code/__tests__/integration/Amplify.test.ts
- amplify/backend/ts-code/src/db/ItemTable.ts
- amplify/backend/ts-code/src/db/Schemas.ts
> GH-143: Change History item id to be called itemId

- .github/workflows/amplify-cd.yml
- amplify/ts-code/__tests__/integration/Amplify.test.ts
- amplify/ts-code/__tests__/unit/api/AddItem.test.ts
- amplify/ts-code/__tests__/unit/handlers/api/AddItem.test.ts
- amplify/ts-code/__tests__/unit/handlers/router/Router.test.ts
- amplify/ts-code/src/api/AddItem.ts
> GH-116: Auto-Supply ID during AddItem

- .github/workflows/amplify-cd.yml
- .github/workflows/backend-ci.yml
- amplify/ts-code/__tests__/integration/Amplify.test.ts
- amplify/ts-code/__tests__/unit/api/AddItem.test.ts
- amplify/ts-code/__tests__/unit/handlers/api/AddItem.test.ts
- amplify/ts-code/src/api/AddItem.ts
- backend-integ-test.js
- backend-test.js
- backend-unit-test.js
- package.json
> GH-147: Fix Integration Tests

- frontend/App.js
- frontend/components/Dashboard/DashboardScreen/index.js
- frontend/components/Dashboard/GroupSelection/index.js
- frontend/components/Dashboard/ListCard/index.js
- frontend/components/Dashboard/ListDropdown/index.js
- frontend/components/Dashboard/ListGroup/index.js
- frontend/components/Dashboard/ListsSection/index.js
- frontend/components/Dashboard/index.js
- frontend/components/DashboardFab/ActionButton/index.js
- frontend/components/DashboardFab/ActionDialog/index.js
- frontend/components/DashboardFab/ActionModal/index.js
- frontend/components/GroupSelector/index.js
- frontend/components/ItemTypeButton/index.js
- frontend/components/ListElement/index.js
- frontend/components/Navigation/Navigator/index.js
- frontend/components/Navigation/RMSIcon/index.js
- frontend/components/Navigation/RMSTabsNavigator/index.js
- frontend/components/Navigation/StackNavigator/index.js
- frontend/components/Navigation/TabsNavigator/index.js
- frontend/components/NewItem/NewItem/index.js
- frontend/components/NewItem/NewItemForm/index.js
- frontend/components/NewItem/NewItemHeader/index.js
- frontend/components/RMSIcon/index.js
- frontend/components/RMSTitle/index.js
- frontend/components/RMSToggleButton/index.js
- package-lock.json
- package.json
Okay, let's try this again. Hopefully everything works this time :)
> GH-126: Added Navigation and finished Dashboard appearance

- amplify/ts-code/src/db/ScheduleTable.ts
- amplify/ts-code/src/db/Schemas.ts
> GH-167: Implement TypeScript Schedule Table

- amplify/ts-code/src/api/AddItem.ts
Updated logic. Was just autogenerating single digits before.
> GH-170: Update Auto-Generated item id

- amplify/ts-code/src/api/AddItem.ts
> GH-175: Fix UniqueId bug

- amplify/ts-code/__tests__/integration/Amplify.test.ts
> GH-179: Integration Tests for Write APIs

- amplify/ts-code/src/db/BatchTable.ts
- amplify/ts-code/src/db/ScheduleTable.ts
- amplify/ts-code/src/db/TagTable.ts
- Promise.all is Asynchronous, which causes problems for the delete from array function.
> GH-193: Delete Items from Array Synchronously

- frontend/components/Dashboard/DashboardScreen/index.js
- frontend/components/ListElement/index.js
- frontend/components/NewItem/NewItemForm/index.js
- frontend/components/SwipeListElement/index.js
- package-lock.json
- package.json
cleaned up the styling in the code, and renamed the branch
> GH-177: Cleaned up code

- frontend/App.js
- frontend/components/Borrow/BorrowFAB.js
- frontend/components/Borrow/BorrowToast.js
Added some components that could be used when the user is borrowing an item.
> GH-181: Added Borrow Components

- amplify/resources/seeds/empty.json
- amplify/resources/seeds/one-name-borrowed.json
- amplify/resources/seeds/one-name-change-description.json
- amplify/resources/seeds/one-name-change-note.json
- amplify/resources/seeds/one-name-change-owner.json
- amplify/resources/seeds/one-name-change-tags.json
- amplify/resources/seeds/one-name-returned.json
- amplify/resources/seeds/one-name-two-items.json
- amplify/resources/seeds/one-name.json
- amplify/resources/seeds/two-names-fail-create.json
- amplify/resources/seeds/two-names-one-batch-borrowed.json
- amplify/resources/seeds/two-names-one-batch-modified.json
- amplify/resources/seeds/two-names-one-batch-partially-borrowed.json
- amplify/resources/seeds/two-names-one-batch-reserved.json
- amplify/resources/seeds/two-names-one-batch-returned.json
- amplify/resources/seeds/two-names-one-batch.json
- amplify/resources/seeds/two-names.json
- amplify/ts-code/__dev__/db/DBTestConstants.ts
- amplify/ts-code/__dev__/db/LocalDBClient.ts
- amplify/ts-code/__tests__/unit/api/CreateReservation.test.ts
- amplify/ts-code/__tests__/unit/api/DeleteReservation.test.ts
- amplify/ts-code/__tests__/unit/api/GetReservation.test.ts
- amplify/ts-code/__tests__/unit/handlers/router/Router.test.ts
- amplify/ts-code/src/api/CreateReservation.ts
- amplify/ts-code/src/api/DeleteItem.ts
- amplify/ts-code/src/api/DeleteReservation.ts
- amplify/ts-code/src/api/GetReservation.ts
- amplify/ts-code/src/db/ScheduleTable.ts
- amplify/ts-code/src/handlers/router/Router.ts
resolves #178 
Backlogging implementation of Update API for now.
Unit tests for APIs
> GH-178: Implement CRUD APIs for Reservation System

- amplify/backend/function/CreateReservation/CreateReservation-cloudformation-template.json
- amplify/backend/function/DeleteReservation/DeleteReservation-cloudformation-template.json
- amplify/team-provider-info.json
- amplify/ts-code/__tests__/integration/Amplify.test.ts
- amplify/ts-code/src/db/ScheduleTable.ts
resolves #199 
Integration Tests passed.
> GH-199: Add Integration Tests for Reservation

- amplify/ts-code/src/handlers/router/SMSRouter.ts
> GH-198: Fixed Router Not Displaying Error Message

- frontend/App.js
- frontend/components/Inventory/InventoryScrollView/index.js
- frontend/components/Inventory/index.js
- frontend/components/ListElement/index.js
- frontend/components/Util/UtilRead.js
- frontend/components/Util/UtilWrite.js
- frontend/store/sliceManager.js
- frontend/store/slices/itemsSlice.js
- frontend/store/store.js
- package-lock.json
- package.json
Hey James can you double-check that this runs on your computer?
> Gh 189/wu chinese new
